### ISSUE TITLE
我打包了一个release文件，这样就不用配环境直接用了

### ISSUE THREAD

**Issue by SunnySlopes** [kaniol-lck/modmanager#1]
好像这里没法发送文件（我也不知道怎么回事）所以文件放蓝奏云了
https://www.lanzouw.com/b020jlqva
密码:5e7h

**Comment by kaniol-lck** [comment]
**你 在 做 什 么 ？**
本项目本来就已经配置了[GitHub Actions](https://github.com/kaniol-lck/modmanager/actions) ，从里面挑个Pass的下载Artifacts就能直接用了。
至于release，只是未到时候，等到我功能完善程序稳定时自然会发布的。

**Comment by Hendrix-Shen** [comment]
> 好像这里没法发送文件（我也不知道怎么回事）所以文件放蓝奏云了
> https://www.lanzouw.com/b020jlqva
> 密码:5e7h

然而你没有发现你打包的程序 **不能用** 嘛（必要dll **一个都没有** 打包）

**Comment by SunnySlopes** [comment]
行，我认错，我以后再也不来你这里掺和了



在 2021-09-18 17:57:26，"Kaniol" ***@***.***> 写道：

你 在 做 什 么 ？
本项目本来就已经配置了GitHub Actions ，从里面挑个Pass的下载Artifacts就能直接用了。
至于release，只是未到时候，等到我功能完善程序稳定时自然会发布的。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
