### ISSUE TITLE
某些Mod无法被发现

### ISSUE THREAD

**Issue by NaiHeKK** [kaniol-lck/modmanager#10]
planttech2 我安装了这个mod但是在这个管理器里却找不到也无法更新

**Comment by NaiHeKK** [comment]
这Mod是Forge的我游戏是Fabric的，也许是bug，也许是设计就是这样？

**Comment by Hendrix-Shen** [comment]
这是 **刻意为之** 的设定。
你不能在设置为 Forge Loader 环境的目录下展示 Fabric Mod，同样也不能在设置为 Fabric Loader 环境的目录下展示 Forge Mod。

**Comment by NaiHeKK** [comment]
> 所以为什么要在fabric中安装forge mod 🤔

忘记删了
0-0
