### ISSUE TITLE
[Bug]: 部分 Mod 无法被检测到

### ISSUE THREAD

**Issue by Logic530** [kaniol-lck/modmanager#16]
### OS Version

Windows

### Version Details(版本信息)

v1.0.0 beta3

### Describe the bug(问题描述)

部分 Mod 无法被检测到，目前发现的包括 Light Overlay 和 Dynamic Surroundings 。
在管理器内重新下载也无法被检测到。
![image](https://user-images.githubusercontent.com/22793670/137056017-c87f5ef9-7968-4b82-ab9e-4897f27ac404.png)

### This issue is unique(这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context(额外说明)

可能是因为这两个mod标注的适配版本较低（1.16.4），但实际能够在高版本使用（1.16.5）

**Comment by kaniol-lck** [comment]
已确认问题：
- light overlay因为fabric和forge为同一jar文件，被优先识别为fabric mod，所以在forge中未能显示，会及时修复。
- dynamic surrounding内的mods.toml文件相对写的比较奔放，我使用的toml库无法解析该toml文件

**Comment by Logic530** [comment]
另外的话能否添加一个功能在mod未能被检测时发出提醒，包括数量和文件名称，方便排查

**Comment by kaniol-lck** [comment]
应该都已经解决了，可以验证一下
