### ISSUE TITLE
[Feature]: 颜色代码

### ISSUE THREAD

**Issue by NewbieXvwu** [kaniol-lck/modmanager#19]
### OS Version

Windows

### Version Details(版本信息)

1.0.0 beta3

### Describe the bug(问题描述)

有些mod的名字使用了颜色代码。（如图）
![image](https://user-images.githubusercontent.com/87637612/137605852-2f98139b-acfa-410d-b794-868235feb327.png)
希望能支持使用颜色代码的mod的名字显示，同时最好添加是否打开该功能的选项。

### To Reproduce(复现问题)

![image](https://user-images.githubusercontent.com/87637612/137605871-3acf3fac-15c3-4302-82fb-fea2a262fcae.png)

### Expected behavior(预期行为)

支持使用颜色代码的mod的名字显示，同时最好添加是否打开该功能的选项。

### This issue is unique(这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context(额外说明)

![image](https://user-images.githubusercontent.com/87637612/137605883-f6fbe8ad-6508-4238-8c64-c27d9722d6ee.png)

**Comment by kaniol-lck** [comment]
not bug, 会马上实现的
