### ISSUE TITLE
[Feature] CurseForge Worlds and ResourcePacks

### ISSUE THREAD

**Issue by tokenspins** [kaniol-lck/modmanager#2]
Add the ability to download/manage worlds and resourcepacks from CurseForge.

**Comment by kaniol-lck** [comment]
Obviously, Mod Manager is **Mod** Manager, so worlds and resource packs won't be managed.
But still, it would be nice and useful to download them (as a *super secret setting*), if i have extra time working on it.

**Comment by buiawpkgew1** [comment]
这个完成了为啥不关闭？

**Comment by kaniol-lck** [comment]
> 这个完成了为啥不关闭？ 2个月了

并没有完全完成，标签分类系统还没有做好

**Comment by SettingDust** [comment]
> 这个完成了为啥不关闭？ 2个月了

看起来现在还无法读取元数据

**Comment by kaniol-lck** [comment]
Done.

**Comment by SettingDust** [comment]
> 并没有完全完成，标签分类系统还没有做好

标签分类系统是指？

> Done.

是不做元数据读取吗？

**Comment by kaniol-lck** [comment]
> 标签分类系统是指？

就这个：
![图片](https://user-images.githubusercontent.com/29243443/147430017-367ebf9b-3ec4-4757-b8b9-d36a7d8f7d7c.png)
![图片](https://user-images.githubusercontent.com/29243443/147430039-f60b3f56-e720-4bfc-87b1-823c15555b8a.png)

> 是不做元数据读取吗？

元数据读取是什么

**Comment by SettingDust** [comment]
> 元数据读取是什么

本地读取资源包元数据…

**Comment by kaniol-lck** [comment]
> 本地读取资源包元数据…

是的，不管理本地的资源包信息
