### ISSUE TITLE
[Feature]: Fabric environment 元数据添加标签

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#20]
### What new features do you want(你想要什么新功能)?

通过判断[环境](https://fabricmc.net/wiki/zh_cn:documentation:fabric_mod_json?s[]=environment)元数据添加标签到模组

### This issue is unique(这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
收到
