### ISSUE TITLE
[Bug] curseforge无法加载

### ISSUE THREAD

**Issue by ajdgsu** [kaniol-lck/modmanager#23]
### OS Version

Windows

### Version Details(版本信息)

1.0.0beta3

### Describe the bug(问题描述)

我的电脑在打开curseforge的时候会被要求做机器人验证，做完就能正常访问curseforge了。但是不论是否有做机器人验证modmanager都无法打开curseforge(别的都可以正常打开)，同时也能正常更新mod(不确定是否是通过别的地址更新的)，点击刷新按钮也没有用

### To Reproduce(复现问题)

应该只要进入curseforge有机器人验证就会出现

### This issue is unique(这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context(额外说明)

我不清楚modmanager是怎样访问curseforge的，(个人怀疑是modmanager使用独立浏览器加载网页导致无法做机器人验证所以不能加载网页)，如果可以的话请告诉我怎样抓它的log

**Comment by Hendrix-Shen** [comment]
Mod Manager 通过 CurseForge API 进行请求，与主站人机验证无关。

**Comment by kaniol-lck** [comment]
所以都说了，我使用的是API，可以 **免代理** 访问curseforge，也 **不可能** 需要人机验证，如有连接问题，是你那边的网络问题，比如运营商的墙中墙
