### ISSUE TITLE
[Bug]: Modrinth 链接无法打开

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#25]
### OS Version

Windows

### Version Details(版本信息)

beta3

### Describe the bug(问题描述)

![图片](https://user-images.githubusercontent.com/19922286/137889546-a1c74cb8-2c0c-4aa7-b0d1-a4eeed09c42b.png)
右上角的按钮不会打开网页，cf 可以，我不清楚哪里看 debug 信息

### This issue is unique(这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
奇怪 我这边没有复现
