### ISSUE TITLE
[Bug]: 在刷新本地列表时下载模组会导致进度条卡住

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#26]
### OS Version

Windows

### Version Details(版本信息)

beta3

### Describe the bug(问题描述)

卡住就是进度条上限增加了，但是实际上没有尝试继续检查，而是走到之前的上限直接呆住，新的东西没加到任务里

### This issue is unique(这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
因为目前还没有考虑此类情况，之后会修复的

**Comment by kaniol-lck** [comment]
在之前某次修改中修复，目前已经不会出现这个情况
（因为下载模组后直接加入本地列表被我x了，后续再重新加入）
