### ISSUE TITLE
beta2设置保存貌似有问题

### ISSUE THREAD

**Issue by weiyici** [kaniol-lck/modmanager#3]
设置完mods文件夹的路径之后，退出重进设置全变成默认

**Comment by kaniol-lck** [comment]
挺奇怪的，beta2我基本没有修改过这访民啊的内容，我这边也没有出现这个问题
beta1中没有这个问题吗？

**Comment by weiyici** [comment]
我这bate1中没有这个问题

**Comment by kaniol-lck** [comment]
知道问题了，是单文件封包的时候把已有配置包含进exe了，所以设置不起作用，压缩包的没问题

**Comment by kaniol-lck** [comment]
文件已更换完毕，重新下载应该就行了
