### ISSUE TITLE
[Question] 为何不再提供免安装版本

### ISSUE THREAD

**Issue by baka-gourd** [kaniol-lck/modmanager#31]
### Question Type (问题类型)

Others (其他)

### Describe the question (描述你的问题)

在最近的actions构件中，不在上传原来的版本，而是只上传打包成installer的。
这不是什么大型应用，完全可以像之前一样提供免安装版本。

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my question.

**Comment by baka-gourd** [comment]
其实win可以直接带个aria2c的二进制来的。。。

**Comment by kaniol-lck** [comment]
> 其实win可以直接带个aria2c的二进制来的。。。

是可以，但以内部库形式调用要优于外部进程间通信
