### ISSUE TITLE
[Bug] 找不到libgcc_s_seh-1.dll

### ISSUE THREAD

**Issue by fengyec2** [kaniol-lck/modmanager#32]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #116

### Describe the bug (问题描述)

打开ModManager提示由于找不到libgcc_s_seh-1.dll，无法继续执行代码。重新安装程序可能会解决此问题

### To Reproduce (复现问题)

1.打开ModManager
2.出现提示

### Expected behavior (预期行为)

正常打开ModManager

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

Nope

**Comment by kaniol-lck** [comment]
看来win与win的体质还是不能一概而论
之后我再打包个带这个dll的

**Comment by kaniol-lck** [comment]
试试 [Actions #118](https://github.com/kaniol-lck/modmanager/actions/runs/1402032916) 中的[构建](https://github.com/kaniol-lck/modmanager/suites/4207967669/artifacts/108691899)

**Comment by fengyec2** [comment]
可以用了😀
