### ISSUE TITLE
[Feature] 添加可导出 CurseForge 格式包的功能

### ISSUE THREAD

**Issue by GBLodb** [kaniol-lck/modmanager#34]
### What new features do you want? (你想要什么新功能)

如题, 希望能添加一个能导出 CurseForge 格式整合包 (主要为 ```manifest.json``` 和 ```modlist.html```) 的功能.

### Additional context (额外说明)

如果不能导出整个包, 仅可导出作为 CurseForge 格式整合包主要组成部分的 ```manifest.json``` 和 ```modlist.html``` 也好.

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
这个会做的，而且在导出功能之前我得先做导入功能

**Comment by kaniol-lck** [comment]
目前已经添加了导出 `manifest.json` 和 `modlist.html` 的功能
