### ISSUE TITLE
[Bug] CF 标签重复

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#36]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

beta5

### Describe the bug (问题描述)

![图片](https://user-images.githubusercontent.com/19922286/140851108-b92fb3e7-478c-4390-8e22-485ff2e509a3.png)
只看到 mousetweak 的标签重复了，其他没看到

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
![图片](https://user-images.githubusercontent.com/29243443/140935709-398acae4-2e4d-4fd6-b31c-72e95954392b.png)
Curseforge的数据如此

**Comment by kaniol-lck** [comment]
现在已经帮它去了个重
