### ISSUE TITLE
[Feature] 重命名可以替换字符 & 记录上次使用的规则

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#37]
### What new features do you want? (你想要什么新功能)

- [x] 加入替换的规则，如 `<replace|+|->`
- [x] 记录上次使用的规则

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
做了这样一个写法：
```
<replace|原始字符串|替换正则表达式|目标字符串>
```

用法如图：
![图片](https://user-images.githubusercontent.com/29243443/142750615-10148751-47b4-428b-aa7e-14585a0f8520.png)
