### ISSUE TITLE
[Bug] 新的分类未显示

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#38]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

beta5

### Describe the bug (问题描述)

![图片](https://user-images.githubusercontent.com/19922286/142090119-51ec7e0f-551d-4e83-90d8-daa108c096b7.png)
![图片](https://user-images.githubusercontent.com/19922286/142090103-1c5f1daa-3ebb-4243-a4bd-b71f526d2706.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
考虑到分类项的翻译以及分类图标的缓存，这部分分类项实为硬编码的
我稍后更新一下这部分代码
