### ISSUE TITLE
[Bug] CF 没有根据创建日期排序的选项

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#39]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

beta5

### Describe the bug (问题描述)

![图片](https://user-images.githubusercontent.com/19922286/142549051-4f5bd610-b3fa-4589-9812-fc808b9f148e.png)
![图片](https://user-images.githubusercontent.com/19922286/142549306-251c2eb2-330c-4601-b338-a811df2953f0.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
是这样的，cursefoege api与网页的排序选项是不一致的
