### ISSUE TITLE
[Bug] AUR 无法编译

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#40]
### OS Version (系统版本)

Linux

### Version Details (版本信息)

r420.82161b9-1

### Describe the bug (问题描述)

```
In file included from src/local/updatable.hpp:9,
                 from src/local/localmod.h:8,
                 from src/curseforge/curseforgemod.cpp:9:
src/download/qaria2downloader.h:6:10: 致命错误：aria2/aria2.h：没有那个文件或目录
    6 | #include <aria2/aria2.h>
      |          ^~~~~~~~~~~~~~~
编译中断。
make: *** [Makefile:2383：curseforgemod.o] 错误 1
==> 错误： 在 build() 中发生一个错误。
    正在放弃...
 -> 生成时出错: modmanager-git
```
```
rc/local/fabricmodinfo.cpp:6:10: 致命错误：quazip.h：没有那个文件或目录
    6 | #include <quazip.h>
      |          ^~~~~~~~~~
编译中断。
make: *** [Makefile:2444：fabricmodinfo.o] 错误 1
==> 错误： 在 build() 中发生一个错误。
    正在放弃...
 -> 生成时出错: modmanager-git

```

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by SettingDust** [comment]
知道原因了，没装 aria2，不能写到依赖信息里吗？而且看起来 README 是错的XD

**Comment by SettingDust** [comment]
第二个的原因是路径对不上，我这边安装 QuaZip 之后在 `/usr/include/QuaZip-Qt5-1.2/`，构建 include 的是 `/usr/include/QuaZip-Qt5-1.1/`

**Comment by SettingDust** [comment]
@Trumeet 维护者

**Comment by kaniol-lck** [comment]
> 知道前一个的原因了，没装 aria2，不能写到依赖信息里吗？而且看起来 README 是错的XD
> 
> https://github.com/kaniol-lck/modmanager/blob/master/README_zh.md?plain=1#L40 `yay -S aria2` 应该是

XD 这就去改

> 第二个的原因是路径对不上，我这边安装 QuaZip 之后在 `/usr/include/QuaZip-Qt5-1.2/`，构建 include 的是 `/usr/include/QuaZip-Qt5-1.1/`

quazip的版本原因，我这里安装的是extra/quazip的1.1版本，而它似乎没放在同样路径或有软链接，我也不是很懂。

目前就依赖了qt、quazip以及aria2库，AUR方面我也不太会弄，还是得靠@Trumeet 麻烦修改一下

**Comment by Trumeet** [comment]
收到，我尽快处理

**Comment by Trumeet** [comment]
> quazip的版本原因，我这里安装的是extra/quazip的1.1版本，而它似乎没放在同样路径或有软链接，我也不是很懂。

对于 quazip 库版本问题，不知作者可否适配一下新版 quazip？Arch Linux 只会包含最新版库，所以 quazip 从 1.1 升级到 1.2 后自然就没有旧版库和头文件了。或者我可以尝试在 AUR 里 Patch 一下代码来让它工作，但不确定能否成功。

@kaniol-lck

**Comment by SettingDust** [comment]
> > quazip的版本原因，我这里安装的是extra/quazip的1.1版本，而它似乎没放在同样路径或有软链接，我也不是很懂。
> 
> 对于 quazip 库版本问题，不知作者可否适配一下新版 quazip？Arch Linux 只会包含最新版库，所以 quazip 从 1.1 升级到 1.2 后自然就没有旧版库和头文件了。或者我可以尝试在 AUR 里 Patch 一下代码来让它工作，但不确定能否成功。
> 
> @kaniol-lck

看起来是 archlinux 的 quazip 没正确创建用于 include 的链接，这样分版本的确实不太正常

**Comment by Trumeet** [comment]
> > > quazip的版本原因，我这里安装的是extra/quazip的1.1版本，而它似乎没放在同样路径或有软链接，我也不是很懂。
> > 
> > 
> > 对于 quazip 库版本问题，不知作者可否适配一下新版 quazip？Arch Linux 只会包含最新版库，所以 quazip 从 1.1 升级到 1.2 后自然就没有旧版库和头文件了。或者我可以尝试在 AUR 里 Patch 一下代码来让它工作，但不确定能否成功。
> > @kaniol-lck
> 
> 看起来是 archlinux 的 quazip 没正确创建用于 include 的链接，这样分版本的确实不太正常

好的。

已将 aria2 和 quazip 加进 PKGBUILD 的 depends 中，现在可以通过编译了。

**Comment by kaniol-lck** [comment]
> > > > quazip的版本原因，我这里安装的是extra/quazip的1.1版本，而它似乎没放在同样路径或有软链接，我也不是很懂。
> > > 
> > > 
> > > 对于 quazip 库版本问题，不知作者可否适配一下新版 quazip？Arch Linux 只会包含最新版库，所以 quazip 从 1.1 升级到 1.2 后自然就没有旧版库和头文件了。或者我可以尝试在 AUR 里 Patch 一下代码来让它工作，但不确定能否成功。
> > > @kaniol-lck
> > 
> > 
> > 看起来是 archlinux 的 quazip 没正确创建用于 include 的链接，这样分版本的确实不太正常
> 
> 好的。
> 
> 已将 aria2 和 quazip 加进 PKGBUILD 的 depends 中，现在可以通过编译了。

感谢维护
