### ISSUE TITLE
[Bug] 检查更新卡住

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#41]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

beta5

### Describe the bug (问题描述)

检查更新的时候卡在最后一个，不知道是哪个模组，会卡几分钟，不知道是超时还是怎么了

### Expected behavior (预期行为)

有具体超时提示 `XXX 检查失败`，超时时间短一点

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
最新构建大概已经解决了这个BUG

**Comment by kaniol-lck** [comment]
似乎没有解决，modrinth的超时似乎有些问题

**Comment by kaniol-lck** [comment]
好了，这回应该是好了

**Comment by SettingDust** [comment]
还是卡住了 
![图片](https://user-images.githubusercontent.com/19922286/143731851-a133ee4d-bb6e-408c-914c-e154e20646e7.png)
2 分钟没动静，还在继续卡着，根据经验来说要 10 分钟或者不会好了，纯碰运气，有时候不会

**Comment by kaniol-lck** [comment]
真要命，老夫回头再找找问题

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/145680490-c8c30e0d-0898-4856-b439-aec5543f825e.png)

**Comment by kaniol-lck** [comment]
> ![image](https://user-images.githubusercontent.com/71136405/145680490-c8c30e0d-0898-4856-b439-aec5543f825e.png)

请问版本是？
建议使用 [actions](https://github.com/kaniol-lck/modmanager/actions) 中的构建测试该问题

**Comment by buiawpkgew1** [comment]
> > ![image](https://user-images.githubusercontent.com/71136405/145680490-c8c30e0d-0898-4856-b439-aec5543f825e.png)
> 
> 请问版本是？ 建议使用 [actions](https://github.com/kaniol-lck/modmanager/actions) 中的构建测试该问题
版本是0.7

**Comment by kaniol-lck** [comment]
> 版本是0.7

beta 7 的话属于已知问题
