### ISSUE TITLE
[Bug] UI 显示问题：部分按钮看不到（也不知道是做什么的）

### ISSUE THREAD

**Issue by Trumeet** [kaniol-lck/modmanager#43]
### OS Version (系统版本)

Linux

### Version Details (版本信息)

master 30dfbdf

### Describe the bug (问题描述)

![image](https://user-images.githubusercontent.com/17158086/143619952-7abc2583-a08b-459d-87ab-84831c98f674.png)

列表每一项都有三个按钮（一个是下拉菜单，点击后会显示一些版本；一个是三个点；一个什么都没有），但都看不到，只有当鼠标移动到按钮上才能看到有这个按钮。

### To Reproduce (复现问题)

Local mods 进去，鼠标移动到列表项右侧版本号附近，就能看到三个按钮。

### Expected behavior (预期行为)

应该有一个 Tooltip 告诉我按钮是做什么的，以及按钮上的图标或文字（如果有）应该正确显示。

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

qt5-base 5.15.2+kde+r260-1
Qt5 default theme
i3wm
X11, 1920 x 1080, no HiDPI

**Comment by kaniol-lck** [comment]
奇怪，看起来是所有主题图标都没有显示出来，linux系统会使用系统主题，而其他系统才会使用程序自带的图标主题：https://github.com/kaniol-lck/modmanager/blob/master/src/main.cpp#L23-L25

尝试切换一下成其他图标主题看看是否还会出现这个问题：系统设置 > 外观 > 图标

**Comment by Trumeet** [comment]
@kaniol-lck

看代码好像是 Hard code 为 KDE Breeze 主题了： `QIcon::setThemeName("breeze-modmanager");` ？我没有装 KDE 也没有装 Breeze 主题 所以不知道是不是这个原因（我不懂 Qt 开发所以可能不太对）

以及没有用 KDE 所以没有 系统设置 > 外观 > 图标

不过我随手找了个配置工具（qt5ct）看了一下，好像是 Adwaita？

![image](https://user-images.githubusercontent.com/17158086/143666014-a33d9c6d-266d-4882-89f4-b8f18fd6b878.png)

**Comment by kaniol-lck** [comment]
> qt5-base 5.15.2+kde+r260-1
我以为你使用的是kde

> 看代码好像是 Hard code 为 KDE Breeze 主题了： `QIcon::setThemeName("breeze-modmanager");` ？我没有装 KDE 也没有装 Breeze 主题 所以不知道是不是这个原因（我不懂 Qt 开发所以可能不太对）
反了，是非Linux系统环境才设置为主题，我是假定linux的桌面环境下应该都有合适的可调用的图标主题，所以在linux下没有设置为“breeze-modmanager”（程序自带的主题）

这么看来你使用的图标主题并不支持这些图标，或者调用不到此处设置的主题，看来我应该将图标主题设置为可设置项而非预定义项

**Comment by Trumeet** [comment]
> > qt5-base 5.15.2+kde+r260-1
> 
> 我以为你使用的是kde
> 

啊 不好意思，这只是 Arch Repo Qt5 的一个版本号（说实话我也觉得很奇怪

> > 看代码好像是 Hard code 为 KDE Breeze 主题了： `QIcon::setThemeName("breeze-modmanager");` ？我没有装 KDE 也没有装 Breeze 主题 所以不知道是不是这个原因（我不懂 Qt 开发所以可能不太对）
> 
> 反了，是非Linux系统环境才设置为主题，我是假定linux的桌面环境下应该都有合适的可调用的图标主题，所以在linux下没有设置为“breeze-modmanager”（程序自带的主题）
> 

啊... ifndef，抱歉眼花了。

> 这么看来你使用的图标主题并不支持这些图标，或者调用不到此处设置的主题，看来我应该将图标主题设置为可设置项而非预定义项

嗯，其实提供一个设置项会更好。

**Comment by kaniol-lck** [comment]
尝试一下最新构建 7c02679

**Comment by Trumeet** [comment]
> 尝试一下最新构建 [7c02679](https://github.com/kaniol-lck/modmanager/commit/7c02679b9095a8e73ab632c89961f928eba86601)

感谢作者，这次工作了。
