### ISSUE TITLE
[Bug] 无法通过主页面左下角的 新建 按钮添加本地mod路径

### ISSUE THREAD

**Issue by fengyec2** [kaniol-lck/modmanager#44]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #211

### Describe the bug (问题描述)

无法通过主页面左下角的 新建 按钮添加本地mod路径（但可以通过 管理 来添加）
![图片](https://user-images.githubusercontent.com/85821538/143665724-a987655e-e6ae-46eb-9692-a1ae3a3b4849.png)

### To Reproduce (复现问题)

1.打开mod manager
2.点击新建
3.选择mod文件夹
4.选择OK
5.页面选择器处未显示新添加的本地mod路径
![图片](https://user-images.githubusercontent.com/85821538/143665788-b30b0bf3-664b-43fd-a99e-44de8f81c2ce.png)

### Expected behavior (预期行为)

希望成功添加新的本地mod路径

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

Nope

**Comment by kaniol-lck** [comment]
点击该按钮应该会弹出对话框一个新建路径的对话框：
![图片](https://user-images.githubusercontent.com/29243443/143666693-c2f6e85c-77c5-43f6-951e-62aae38167b1.png)

不是很懂为什么它会显示不了，先尝试一下能否通过快捷键 `Ctrl+Shift+N` 或 *菜单 > 路径 > 新建路径 > 打开新建路径对话框* 呼出该对话框
![图片](https://user-images.githubusercontent.com/29243443/143666778-e91a7428-67a7-4835-98a3-892b76781d79.png)

**Comment by kaniol-lck** [comment]
抱歉，是个愚蠢的错误，我马上修复

**Comment by kaniol-lck** [comment]
已修复
