### ISSUE TITLE
[Bug] 本地 Mod 介绍被句点断开

### ISSUE THREAD

**Issue by LLLingMo** [kaniol-lck/modmanager#46]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

beta.7

### Describe the bug (问题描述)

如题，如果 mcmod.info 里的 description 中有句点，则：

- 本地mod查看时，默认(似乎)在右上角的预览窗格只显示句点及之前的部分。
- 本地mod查看时，列表中如果用第一种视图，同上不能正常显示；第三种视图(表格)可正常显示。
- 本地mod查看时，默认(似乎)在右下角的选版本的窗格可正常显示。
- 本地mod查看时，双击之后弹出的窗口可以正常显示。

句点指的是：
> .

![image](https://user-images.githubusercontent.com/49084094/143681940-891fa6ed-43c3-4449-a1a1-fc4695026f64.png)
![image](https://user-images.githubusercontent.com/49084094/143681954-79ea3111-6eba-4a8a-8bca-a69d4137af0c.png)

(第一张因看不完全右下角的版本选择，我篡改了第二张图的 mod 的 mcmod.info)

### To Reproduce (复现问题)

任意本地文件夹 mod 描述中有半角句点且不是最后一个字符应可复现

### Expected behavior (预期行为)

应正常显示句点以后部分。

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
这个最开始加入从句号截断是有意为之的，为了防止列表中过长显示不美观，不过现在考虑一下也许是画蛇添足了
