### ISSUE TITLE
[Bug] 列表显示模式为后两个的时候标题渲染会出错

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#47]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

https://github.com/kaniol-lck/modmanager/commit/93b7e1990b3fe0603f139e2fe7e320937d6d1467

### Describe the bug (问题描述)

![图片](https://user-images.githubusercontent.com/19922286/143731603-2a204f19-8b6d-46e4-ac77-376b877bfcb9.png)

![图片](https://user-images.githubusercontent.com/19922286/143731736-9693d16c-5e82-4d03-b013-ee26e7e73d4f.png)

顺带，禁用颜色没有覆盖原本标题色 lul
![图片](https://user-images.githubusercontent.com/19922286/143731808-9148061b-75ee-4202-8ee0-f359edf9f28b.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
![图片](https://user-images.githubusercontent.com/29243443/143735276-110e911c-2f58-48e4-908d-335a8242c260.png)
![图片](https://user-images.githubusercontent.com/29243443/143735310-e3c0fc13-3299-4dea-9e90-52edf6e901e2.png)
![图片](https://user-images.githubusercontent.com/29243443/143735291-3160cc6f-82ba-4616-85cc-f5cdc5a39133.png)
