### ISSUE TITLE
[Feature] 新的显示模式下被禁用模组效果仅让图片黑白不明显

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#48]
### What new features do you want? (你想要什么新功能)

添加明显标识，例如名字前添加🈲或🚫，或者像第一个模式文字也变成灰色
如图，很不明显，尤其在选中之后几乎无法识别，且存在本身就是黑白的图片
![图片](https://user-images.githubusercontent.com/19922286/143731667-f32aef2a-d983-4c58-8125-01a24f9cb2f5.png)

> 且存在本身就是黑白的图片

引申出第二个模式也存在同样问题
![图片](https://user-images.githubusercontent.com/19922286/143731713-ea525a54-ed3c-4f22-9f25-1acbc0e1e55a.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
![图片](https://user-images.githubusercontent.com/29243443/143763411-2371be75-af1b-4a47-9bf5-0e8a91a9827a.png)

**Comment by baka-gourd** [comment]
#11 中已经有提到部分，终于有人再提了（
