### ISSUE TITLE
[Feature] 希望可以添加对代理的支持

### ISSUE THREAD

**Issue by WallBreakerNO4** [kaniol-lck/modmanager#49]
### What new features do you want? (你想要什么新功能)

由于众所周知的原因，在大陆访问部分下载网站速度较慢，希望可以添加代理功能

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
这玩意使用API应该都是免代理的，即便在大陆也应该能正常访问的。

至于代理，走全局代理不可以吗，我不是很清楚

**Comment by WallBreakerNO4** [comment]
> 这玩意使用API应该都是免代理的，即便在大陆也应该能正常访问的。
> 
> 至于代理，走全局代理不可以吗，我不是很清楚

但访问速度不佳啊，我使用校园网在下载时会有时下载不动

全局代理 不方便，难以分流，一般是关掉的，还是希望能自定义代理

**Comment by kaniol-lck** [comment]
加了 我不清楚用起来怎样，因为我自己一直都是全局代理的
