### ISSUE TITLE
[Bug] "检查更新"按钮显示英文

### ISSUE THREAD

**Issue by leok77** [kaniol-lck/modmanager#51]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

beta8-x64

### Describe the bug (问题描述)

本地路径中的"检查更新"按钮显示英文，语言不统一

![image](https://user-images.githubusercontent.com/54049062/145744253-2c729fcd-f7a0-4da5-b17c-b8e469060dda.png)

### To Reproduce (复现问题)

点击任意一个本地路径，然后查看"检查更新"按钮

### Expected behavior (预期行为)

整体语言应统一，显示"检查更新"

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
忘加翻译了orz
