### ISSUE TITLE
[Bug] v1.0.0 beta8 无法更新mod

### ISSUE THREAD

**Issue by ajdgsu** [kaniol-lck/modmanager#52]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

v1.0.0 beta8

### Describe the bug (问题描述)

我把mod manager升级到v1.0.0 beta8版本之后就没法更新mod了，会一直卡在检查更新这里 (如图) ；
![Snipaste_2021-12-13_11-00-37](https://user-images.githubusercontent.com/45306865/145745945-af97c01a-dafd-4272-bd3a-36d33dc5cc8b.png)
![Snipaste_2021-12-13_11-01-25](https://user-images.githubusercontent.com/45306865/145745951-217f6084-f3a0-4a7f-a440-f473e46277ac.png)

它会一直卡在这里，不过确实可以正常下载mod；其次我测试了v1.0.0 beta7，这个版本是可以正常更新的。

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

在这三mc版本里有的能检查几个mod才会卡住，有的一个也检查不了；同样我也试了清除未匹配的文件链接缓存，但是还是会卡住 (显示链接mod文件中)

**Comment by kaniol-lck** [comment]
又是 #41 的问题，我会尝试努力排除

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/146003993-22f4a536-bf76-4034-ae9d-7a8b3bc6bf80.png)
难道要挂vpn？

**Comment by kaniol-lck** [comment]
> ![image](https://user-images.githubusercontent.com/71136405/146003993-22f4a536-bf76-4034-ae9d-7a8b3bc6bf80.png)
> 难道要挂vpn？
> 等半小时了

试试 [最新Actions中的构建](https://github.com/kaniol-lck/modmanager/actions/runs/1577743780)

**Comment by buiawpkgew1** [comment]
> > ![image](https://user-images.githubusercontent.com/71136405/146003993-22f4a536-bf76-4034-ae9d-7a8b3bc6bf80.png)
> > 难道要挂vpn？
> > 等半小时了
> 
> 试试 [最新Actions中的构建](https://github.com/kaniol-lck/modmanager/actions/runs/1577743780)

可以了

**Comment by shenjackyuanjie** [comment]
> > ![image](https://user-images.githubusercontent.com/71136405/146003993-22f4a536-bf76-4034-ae9d-7a8b3bc6bf80.png)
> > 难道要挂vpn？
> > 等半小时了
> 
> 试试 [最新Actions中的构建](https://github.com/kaniol-lck/modmanager/actions/runs/1577743780)

Actions 323的build-又坏了

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/146202597-9ba9c5e0-fe37-4168-890c-3dcd457ffbf6.png)

**Comment by kaniol-lck** [comment]
> > > ![image](https://user-images.githubusercontent.com/71136405/146003993-22f4a536-bf76-4034-ae9d-7a8b3bc6bf80.png)
> > > 难道要挂vpn？
> > > 等半小时了
> > 
> > 
> > 试试 [最新Actions中的构建](https://github.com/kaniol-lck/modmanager/actions/runs/1577743780)
> 
> Actions 323的build-又坏了

此处的链接为 CI#330 ，显然 330 > 323

**Comment by shenjackyuanjie** [comment]
*Cl  332

**Comment by kaniol-lck** [comment]
> ![image](https://user-images.githubusercontent.com/54507071/146202597-9ba9c5e0-fe37-4168-890c-3dcd457ffbf6.png)

你确定这是CI #332 吗？我认为332时候的状态栏已经不长这样了

**Comment by shenjackyuanjie** [comment]
hmmm
旗旗怪怪，目前看起来是没问题了，我在测试测试别的包

**Comment by abcdesteve** [comment]
> > > ![image](https://user-images.githubusercontent.com/71136405/146003993-22f4a536-bf76-4034-ae9d-7a8b3bc6bf80.png)
> > > 难道要挂vpn？
> > > 等半小时了
> > 
> > 
> > 试试 [最新Actions中的构建](https://github.com/kaniol-lck/modmanager/actions/runs/1577743780)
> 
> Actions 323的build-又坏了

为什么actions中的压缩包下载以后总是损坏呢？是我哪一步搞错了吗

**Comment by kaniol-lck** [comment]
> 为什么actions中的压缩包下载以后总是损坏呢？是我哪一步搞错了吗

你的网络问题，下载GitHub上的东西建议挂上梯子
