### ISSUE TITLE
[Feature] 允许被禁用的mod更新

### ISSUE THREAD

**Issue by ajdgsu** [kaniol-lck/modmanager#53]
### What new features do you want? (你想要什么新功能)

我不太清楚别人的mod目录下是什么样的，但至少我会经常添加一些互相冲突的mod (如iris和Sodium) 以便在需要时互相切换，或者一些不常用的mod (如Simple Voice Chat) 。这些mod都是禁用状态的，但并不意味着我永久不再使用它们了，况且就算不再使用也不意味不能更新啊，再不济也可以默认不勾选更新，需要用户手动勾选后再更新。也不至于完全不让选，非得把禁用解除掉之后才能更新吧。

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
done
