### ISSUE TITLE
[Bug] 编辑本地Mod路径时崩溃

### ISSUE THREAD

**Issue by fengyec2** [kaniol-lck/modmanager#55]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #344

### Describe the bug (问题描述)

在主页左侧右键路径，选择编辑，更改名字，选择OK，Manager崩溃

在主页左侧右键路径，选择删除，Manager崩溃

<img width="744" alt="屏幕截图 2021-12-17 232515" src="https://user-images.githubusercontent.com/85821538/146568350-b082e453-a3d8-49dd-a129-884307fa4e89.png">

![QQ图片20211217232547](https://user-images.githubusercontent.com/85821538/146568462-fcce7571-ba43-4c53-8e94-c459e44f5675.png)

### To Reproduce (复现问题)

1.在主页左侧右键路径，
2.选择编辑，
3.更改名字，
4.选择OK，
5.Manager崩溃

1.在主页左侧右键路径，
2.选择删除，
3.Manager崩溃

### Expected behavior (预期行为)

Manager正常工作

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

Nope

**Comment by kaniol-lck** [comment]
收到，应该是在 5298b76 中引入的问题

**Comment by kaniol-lck** [comment]
已修复
