### ISSUE TITLE
[Bug] 寻找新的mod

### ISSUE THREAD

**Issue by buiawpkgew1** [kaniol-lck/modmanager#57]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

0.8 测试版

### Describe the bug (问题描述)

寻找新的mod点击 Curseforge没反应

### To Reproduce (复现问题)

寻找新的mod点击 Curseforge没反应

### Expected behavior (预期行为)

寻找新的mod点击 Curseforge没反应

### This issue is unique (这个issue是唯一的)

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

Uploading 1639814565954.mp4…

**Comment by buiawpkgew1** [comment]
我小白

**Comment by buiawpkgew1** [comment]
我小白

**Comment by kaniol-lck** [comment]
如 ff06bea 所说，暂时关闭了此功能。
因为在重构相关代码
