### ISSUE TITLE
[Bug] modrinth 搜索时选择加载器和版本后只有版本生效了

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#58]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #358

### Describe the bug (问题描述)

![图片](https://user-images.githubusercontent.com/19922286/147381101-15e29e75-2128-4c79-a4ea-33be38b28ef4.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
已修复，不知道什么时候给玩坏了
