### ISSUE TITLE
[Feature] 下载按钮禁用效果不明显

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#59]
### What new features do you want? (你想要什么新功能)

希望可以明显点xd，上面是已下载的
![图片](https://user-images.githubusercontent.com/19922286/147381218-d39eb1aa-555a-4082-b2c8-517b0a2b0267.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
给禁用状态下的颜色加深了一点：
![图片](https://user-images.githubusercontent.com/29243443/147388530-89cfc6a9-af6f-44f0-82b9-6c1be7e90ab6.png)
