### ISSUE TITLE
[Feature] 添加打开网页按钮到右侧详情

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#60]
### What new features do you want? (你想要什么新功能)

添加一个打开网页的按钮到详情，位置举例（个人觉得点标题最好xd）：
![图片](https://user-images.githubusercontent.com/19922286/147381442-a8482b5f-13e2-411a-a196-9d4b40aaca56.png)
可以小三角下拉，或者两个小按钮
![图片](https://user-images.githubusercontent.com/19922286/147381501-5d07b638-c607-4b6e-a666-895590d8907e.png)

可以不用双击弹出对话框再跳转了

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
已完成
