### ISSUE TITLE
[Bug] 删除该mod路径

### ISSUE THREAD

**Issue by buiawpkgew1** [kaniol-lck/modmanager#61]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

新测试版

### Describe the bug (问题描述)

删除该mod路径

### To Reproduce (复现问题)

然后

### Expected behavior (预期行为)

出见
![image](https://user-images.githubusercontent.com/71136405/147386107-a2a503d5-b28a-40c6-8d76-62d0366bdb36.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by buiawpkgew1** [comment]
版本是 https://github.com/kaniol-lck/modmanager/actions/runs/1621235638

**Comment by kaniol-lck** [comment]
已修复
