### ISSUE TITLE
[Bug] 更新模组失败

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#62]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #358

### Describe the bug (问题描述)

失败了，但好像又成功了，但是却失败了
![图片](https://user-images.githubusercontent.com/19922286/147401789-de0dba13-79a2-4fe6-b100-ea5b61c9caa5.png)
![图片](https://user-images.githubusercontent.com/19922286/147401774-2219f0fb-7423-482a-8c3e-d030cb143ced.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
#18 因为还没有提示更新失败原因
不过一般是更新前后实际加载器版本不一致或被更新的文件被占用导致的

**Comment by SettingDust** [comment]
但是应该是没占用的，我手动删除是可以的……
forge 更是没更新……

**Comment by SettingDust** [comment]
我手动删除然后重新加载就好了

**Comment by kaniol-lck** [comment]
> 不过一般是更新前后实际加载器版本不一致或被更新的文件被占用导致的

\*加载器类型 防止从fabric mod更新成为forge mod, 因为网站标注的不一定靠谱

**Comment by SettingDust** [comment]
> *加载器类型 防止从fabric mod更新成为forge mod, 因为网站标注的不一定靠谱
是一致的，因为这个模组只有 forge

**Comment by kaniol-lck** [comment]
> 是一致的，因为这个模组只有 forge

所以可能还是占用的问题，重命名失败了，至于怎么占用的咱也不清楚
毕竟产生失败的逻辑只有这两条

**Comment by SettingDust** [comment]
我下一次看看是不是占用，因为我两个实例更新这个模组都失败，其中一个是服务端，两个端都没运行
