### ISSUE TITLE
[Bug] CF 更新不检测 Alpha

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#63]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #358

### Describe the bug (问题描述)

![图片](https://user-images.githubusercontent.com/19922286/147401849-fa13bb55-981b-4f73-a4cd-ac9f2c7a1abe.png)
![图片](https://user-images.githubusercontent.com/19922286/147401854-fd14bdd3-c7db-44e9-adfb-d2bf5c1e4ae4.png)
![图片](https://user-images.githubusercontent.com/19922286/147401873-1878335e-9987-4c75-ad3e-3322f5683c03.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
抱歉 是个愚蠢的typo
