### ISSUE TITLE
[Bug] CF 分类又改了

### ISSUE THREAD

**Issue by SettingDust** [kaniol-lck/modmanager#64]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #358

### Describe the bug (问题描述)

![图片](https://user-images.githubusercontent.com/19922286/147405126-6a148842-94b3-4d67-97d9-e49f0793c7fd.png)
![图片](https://user-images.githubusercontent.com/19922286/147405133-639e4013-30a0-495f-8572-3eaa9f2c8b8d.png)

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
API的分类与CF网页端并不一致，API中获取到的存在这些分类，有些分类无法获取到信息，我也不知道是不是CF有什么问题

**Comment by kaniol-lck** [comment]
把这些没有信息的分类去掉了
