### ISSUE TITLE
[Feature] 从mods文件夹的子文件夹内读取模组

### ISSUE THREAD

**Issue by ChromaPIE** [kaniol-lck/modmanager#65]
### What new features do you want? (你想要什么新功能)

如无技术性困难，Mod Manager可以或提供选项使其可以载入mods下的文件夹内的模组文件吗？

### Additional context (额外说明)

这一特性可以使Mod Manager支持[该模组](https://www.mcmod.cn/class/5353.html)，该模组可方便用户以建立下级文件夹的方式在本地的资源管理器中对模组进行分类整理等操作。

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
已支持该功能。
子文件夹内的mod会载入并添加子文件夹的标签提示：
![图片](https://user-images.githubusercontent.com/29243443/147764063-9605c098-e7cf-4376-b5b3-faddf85e6135.png)
