### ISSUE TITLE
[Bug] 禁用mod置底功能失效

### ISSUE THREAD

**Issue by leok77** [kaniol-lck/modmanager#67]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #386

### Describe the bug (问题描述)

即使是在点击"重新加载mod"之后，"禁用mod置底"功能依旧失效

![偏好设置未关闭此功能](https://user-images.githubusercontent.com/54049062/147901438-44fef6ef-8d74-4c60-ae56-505c868ec9d0.png)

![被禁用的mod并没有置底](https://user-images.githubusercontent.com/54049062/147901457-d1fa428c-8e6d-48d0-8857-b973b4da5ca9.png)

### To Reproduce (复现问题)

下载构建版本CI#386，打开一个含禁用mod的本地路径，查看被禁用的mod是否置底

### Expected behavior (预期行为)

"已禁用的mod置底"功能可用

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
在 7d8425a 开始重构此处的item model，所以本地mod列表这块并没有恢复正常的功能，包括子文件夹mod也没有显示
如果需要正常的功能，请使用这之前的版本（CI#384）或等待重构完成

**Comment by kaniol-lck** [comment]
置顶与置底已恢复
