### ISSUE TITLE
[Bug] 下载新mod无法保存到本地路径

### ISSUE THREAD

**Issue by leok77** [kaniol-lck/modmanager#68]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI#248-CI#388

### Describe the bug (问题描述)

在CF或者Modrinth页面，将"保存至"设置为某一个本地路径；或者是在本地路径处点击"获取新mod"跳转到CF、Modrinth页面之后：
1.点击"打开文件夹"，打开的文件管理器是"此电脑"(比如CI#388)或"此电脑\下载"(比如CI#248)，而不是预期的打开指定本地路径
2.下载任一mod，此mod被保存到"此电脑\下载"，而不是预期的制定的本地路径

此问题是从CI#248开始出现的，CI#247表现正常，其中1一开始表现为打开的是"此电脑\下载"，后面才变成打开"此电脑"
猜测是没有进行路径更新，因为"更新mod"功能是正常使用的。

### To Reproduce (复现问题)

在CF或者Modrinth页面，将"保存至"设置为某一个本地路径；或者是在本地路径处点击"获取新mod"跳转到CF、Modrinth页面之后：
1.点击"打开文件夹"
2.下载任一mod，查看mod保存位置

### Expected behavior (预期行为)

新下载的mod在指定本地路径的情况下应下载到本地路径，而不是在"自定义"文件夹或"此电脑\下载"

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

手动二分测出来的bug最开始的出现位置，希望有帮助

**Comment by kaniol-lck** [comment]
感谢测试了这么多版本，现在已经修复了

**Comment by leok77** [comment]
我测试了一下修复此bug的CI#391，以及最新构建CI#393，下载的新mod已经可以正确保存；
但是"打开文件夹"按钮打开的依旧是"此电脑"，虫还没完全修好。
(我不应该在问题描述中用序号，导致看起来像是操作步骤，实际是两个小问题，my bad)

![image](https://user-images.githubusercontent.com/54049062/147995475-37edd522-664d-4f2a-8595-297f0f1a2bcb.png)

**~~另外一个十点就睡觉的人对快十二点还在搞开发的飞飞发出了"你好肝啊"的声音，建议保证充足睡眠~~**

**Comment by kaniol-lck** [comment]
> 但是"打开文件夹"按钮打开的依旧是"此电脑"，虫还没完全修好。

windows限定的虫（
过会调试一下

**Comment by kaniol-lck** [comment]
> 但是"打开文件夹"按钮打开的依旧是"此电脑"，虫还没完全修好。

修好了
