### ISSUE TITLE
[Bug] 用modmanager更新Fabric Shield API时更新错误，更新至了More Shield。

### ISSUE THREAD

**Issue by ffffffffawd** [kaniol-lck/modmanager#69]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

1.0.0-beta7

### Describe the bug (问题描述)

在用ModManager更新Fabric Shield API时错误更新至了More Shield

### To Reproduce (复现问题)

更新Fabric Shield API，然后发现变成了More Shield，图片倒一样

### Expected behavior (预期行为)

更新正确的mod

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ffffffffawd** [comment]
现在好像不可复现了

**Comment by kaniol-lck** [comment]
无法理解是发生了什么，更新是使用的文件哈希进行比对，不会更新至错误的mod，等能复现了再说

**Comment by ffffffffawd** [comment]
又可以复现了

**Comment by ffffffffawd** [comment]
https://user-images.githubusercontent.com/87227557/149623462-4caf6080-3a8b-470b-ac49-6b0be1a7d673.mp4

**Comment by ffffffffawd** [comment]
![image](https://user-images.githubusercontent.com/87227557/149623560-9c343f82-1984-4e13-832d-c9dc59d525d0.png)

**Comment by ffffffffawd** [comment]
确定是哈希校验？
再加个MD5和SHA-256校验

**Comment by ffffffffawd** [comment]
@kaniol-lck

**Comment by kaniol-lck** [comment]
> 确定是哈希校验？ 再加个MD5和SHA-256校验

curseforge使用murmurhash modrinth使用sha1
这不是我说了算的，就算哈希冲突了也不是我能解决的

我不知道你是怎么链接别的mod的，建议使用菜单中的“在Modrinth中搜索”手动选择。

**Comment by ffffffffawd** [comment]
应该是为了节省空间，不然为什么Modrinth要用SHA-1

https://user-images.githubusercontent.com/87227557/149700425-85149bd9-0794-4127-9148-16143af673c2.mp4

**Comment by ffffffffawd** [comment]
建议向Modrinth提出错误

**Comment by ffffffffawd** [comment]
且只有Modrinth出现了错误

**Comment by kaniol-lck** [comment]
> 建议向Modrinth提出错误

你的意思是它哈希冲突了吗

**Comment by ffffffffawd** [comment]
雀氏
SHA-1已经经过了碰撞测试
两份文件不同
哈希值却一样

**Comment by kaniol-lck** [comment]
> 两份文件不同
> 哈希值却一样

有意思，发一下文件让我看一看

**Comment by ffffffffawd** [comment]
我没文件
百科看来的
![image](https://user-images.githubusercontent.com/87227557/150086284-cf8fa0f4-3dd7-4a65-b03d-6baa34609d65.png)
😪

**Comment by ffffffffawd** [comment]
找到了
[1](http://shattered.io/static/shattered-1.pdf)
[2](http://shattered.io/static/shattered-2.pdf)

**Comment by ffffffffawd** [comment]
感兴趣就看看
自己验证一下
给个网址
[SHAttered](http://shattered.io/)

**Comment by ffffffffawd** [comment]
@kaniol-lck

**Comment by ffffffffawd** [comment]
给个Modrinth反馈的网址我
我要去叭叭(doge)

**Comment by kaniol-lck** [comment]
> 百科看来的 ![image](https://user-images.githubusercontent.com/87227557/150086284-cf8fa0f4-3dd7-4a65-b03d-6baa34609d65.png) sleepy

我是说这两个mod文件是发生哈希冲突了吗，不是sha1这个算法有没有哈希冲突

> 给个Modrinth反馈的网址我
> 我要去叭叭(doge)

https://github.com/modrinth/labrinth
这个是Modrinth后端的仓库

**Comment by ffffffffawd** [comment]
wssb
不会验证是不是
Sorry
