### ISSUE TITLE
[建议]添加本地文件夹时能同时扫描并处理子目录

### ISSUE THREAD

**Issue by Ryen1024** [kaniol-lck/modmanager#7]
如题，导入以前整理的本地Mod库时发现不认子文件夹，一个个手工添加非常痛苦……

**Comment by kaniol-lck** [comment]
子目录具体是要什么形式的呢？毕竟在实际游戏的mod加载器中并不会识别子文件夹的。
是指一个mod路径下有若干正在使用的mod以及存有暂时不用mod的子文件夹还是多个mod路径自动分别导入？

**Comment by kaniol-lck** [comment]
可以考虑这一类功能，如果只是要递归导入可能还是比较容易的，不过若是考虑到保留按文件夹分类，将每个子文件夹路径作为标签，然后通过筛选进行管理（？）

但是这样会混杂游戏版本，我觉得可能将不同的游戏版本作为不同路径管理分别导入，只将功能类作为子文件夹，因为我使用游戏版本来作为更新检查的依据，而一个mod路径理应只有一个游戏版本

我不清楚这样合不合适，如果可以的话就按这么做（虽然按标签筛选还在TODO）

**Comment by SettingDust** [comment]
> 
> 
> 子目录具体是要什么形式的呢？毕竟在实际游戏的mod加载器中并不会识别子文件夹的。 是指一个mod路径下有若干正在使用的mod以及存有暂时不用mod的子文件夹还是多个mod路径自动分别导入？

https://modrinth.com/mod/nnL5V3uf 类似这样的模组，可以选择额外模组文件夹启动

**Comment by kaniol-lck** [comment]
> https://modrinth.com/mod/nnL5V3uf 类似这样的模组，可以选择额外模组文件夹启动

这个mod有意思

**Comment by kaniol-lck** [comment]
done
