### ISSUE TITLE
[Feature] 网络代理

### ISSUE THREAD

**Issue by LIPiston** [kaniol-lck/modmanager#70]
### What new features do you want? (你想要什么新功能)

在偏好设置的网络中，提供代理的选项，自己填写ip和端口，以便提升加载各大平台的速度

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by kaniol-lck** [comment]
是已加入的功能 #49 
请等待Release或使用CI版
