### ISSUE TITLE
[BUG] Fabric Forge mod类型检测错误

### ISSUE THREAD

**Issue by shenjackyuanjie** [kaniol-lck/modmanager#71]
对于`JSmacros`MOD
https://github.com/wagyourtail/JsMacros
每次在更新的时候，版本选择都自动选择了 `FORGE`版本而非 `FABRIC` 版本

modmanager版本：[Cl#436](https://github.com/kaniol-lck/modmanager/actions/runs/1698335441)

**Comment by Hendrix-Shen** [comment]
![image](https://user-images.githubusercontent.com/25112869/149609287-d8f5e28f-af22-4d8d-aead-9bb9a3c0cc9d.png)
确认 a9e2be2 中复现此问题

**Comment by Hendrix-Shen** [comment]
> 对于`JSmacros`MOD https://github.com/wagyourtail/JsMacros 每次在更新的时候，版本选择都自动选择了 `FORGE`版本而非 `FABRIC` 版本
> 
> modmanager版本：[Cl#436](https://github.com/kaniol-lck/modmanager/actions/runs/1698335441)

另外上报BUG请使用 issue template

**Comment by Hendrix-Shen** [comment]
附加信息：该模组在Curseforge项目中，Forge版本未注明模组加载器类型，Fabric版本注明为Fabric模组加载器。

**Comment by kaniol-lck** [comment]
> 附加信息：该模组在Curseforge项目中，Forge版本未注明模组加载器类型，Fabric版本注明为Fabric模组加载器。

人家没标什么加载器类型我能咋办，当然是只能下载下来看看咯，然后更新的时候反正会报更新失败的。
所以说，确认更新前请先检查版本号，如果不想要这个Forge版本大可以选择忽略这个更新并选择一个Fabric版本的

**Comment by shenjackyuanjie** [comment]
或者考虑如果没有标就看看文件名称有没有标识？

**Comment by kaniol-lck** [comment]
> 或者考虑如果没有标就看看文件名称有没有标识？

也不是不可以，但并不完全可靠

**Comment by shenjackyuanjie** [comment]
> > 或者考虑如果没有标就看看文件名称有没有标识？
> 
> 也不是不可以，但并不完全可靠

确实，（先加上正则匹配再说吧（逃
