### ISSUE TITLE
[Bug] 小部分模组无法在列表内显示

### ISSUE THREAD

**Issue by BenjaminLee-Microsoft** [kaniol-lck/modmanager#73]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

v1.0.0-beta.9，CI #447

### Describe the bug (问题描述)

我的自制整合包里有175个mod，在ModManager内点击“重新加载mods“后右下方进度条显示读取到的mod数量正确，也是175个。可是加载完成以后却只有”共计161个mod“。（筛选中已经设置为显示全部）
缺失的mod其中之一是更多门作者的MalisisBlocks，这是该Mod的CurseForge链接[https://www.curseforge.com/minecraft/mc-mods/malisisblocks](url)。
如果这是一些mod自身的问题无法解决，那是否可以加入弹窗提示什么mod没有显示出来呢？这样可以更方便的自己去检查剩下那些mod的更新

![8b60286bd5abdd610ad1b12881b7b25](https://user-images.githubusercontent.com/63907030/150421233-25caea21-103e-40ec-942d-ef02831234e0.png)
如图，mod文件夹里有MalisisBlocks但是搜索不到

### To Reproduce (复现问题)

部分mod（暂未发现共同点，有的是API，有的添加了一点小工具）会100%导致bug出现，且每个ModManager大版本都有这个问题

### Expected behavior (预期行为)

能将mods文件夹内所有的mod都呈现在ModManager的列表里

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
判断是否为mod为读取jar中的mcmod.info或mods.toml文件信息（Forge），没有这些文件mod加载器也不会读取mod，这个MalisisBlocks的mcmod.info塞在其他路径中所以没有读取出来。
![图片](https://user-images.githubusercontent.com/29243443/150455016-31d090ad-3444-4f9e-8b38-71d1c278a82d.png)
MalisisBlocks现已能够显示，看看还有没有别的未显示mod
