### ISSUE TITLE
[Bug] 本地路径搜索Mod之后列表Mod变少

### ISSUE THREAD

**Issue by leok77** [kaniol-lck/modmanager#76]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

V1.0.1

### Describe the bug (问题描述)

本地路径中使用搜索功能，得不到想要搜索的结果，且每次搜索之后Mod列表中的Mod会变少，比如此视频中，Mod列表本身存在appleskin，但是搜索appleskin并不能得到此mod，且清空搜索框之后包含appleskin在内的大量mod不再出现在列表中

https://user-images.githubusercontent.com/54049062/150642031-f3e4876f-9df9-48a6-8e7f-293b164da399.mp4

### To Reproduce (复现问题)

在本地路径的搜索框中搜索任一mod，查看搜索结果；
清空搜索框，查看mod列表

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
嘶，确实， 我明天找一下原因
筛选里面点一下显示全部大概可以恢复显示

**Comment by leok77** [comment]
点了筛选里的显示全部之后恢复显示了，而且搜索功能也可用了。。
