### ISSUE TITLE
[Bug] 非无边框界面的菜单栏寄了

### ISSUE THREAD

**Issue by leok77** [kaniol-lck/modmanager#77]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

V1.0.1

### Describe the bug (问题描述)

V1.0.0正常显示，1.0.1的非无边框界面的菜单栏寄了；
结合更新日志，修了无边框界面的菜单栏问题，把非无边框界面的菜单栏弄出虫了

![image](https://user-images.githubusercontent.com/54049062/150662362-a41c5882-41d1-44e8-9dc2-c82502a25fce.png)

### To Reproduce (复现问题)

偏好设置取消勾选无边框界面，查看菜单栏位置

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kaniol-lck** [comment]
寄
