### ISSUE TITLE
[Bug] mod检查更新版本错误

### ISSUE THREAD

**Issue by fengyec2** [kaniol-lck/modmanager#84]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

CI #538

### Describe the bug (问题描述)

我同时有1.18.1和1.18.2两个版本，但1.18.1的mod检查更新会检查出1.18.2的更新，并且我确定他们不通用。1.18.2同理

<img width="745" alt="Snipaste_2022-03-05_09-30-18" src="https://user-images.githubusercontent.com/85821538/156862656-bcfc9c2d-9ff7-475a-be39-bc7c108093cc.png">
<img width="745" alt="Snipaste_2022-03-05_09-30-49" src="https://user-images.githubusercontent.com/85821538/156862660-079ed909-c2e8-414c-b230-950e44a45056.png">

### To Reproduce (复现问题)

1.启动modmanager
2.选择1.18.1/1.18.2
3.检查更新

### Expected behavior (预期行为)

不要检查到不合适的更新

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

Nope

**Comment by Hendrix-Shen** [comment]
尝试修改 `偏好设置` -> `本地` -> `更新` -> `游戏版本匹配` 为 `小版本号`

**Comment by fengyec2** [comment]
原来是我的问题，解决了
