### ISSUE TITLE
[Bug] 无法连接到curseforge，并且mod因为网络原因更新检查失败

### ISSUE THREAD

**Issue by Pico23th** [kaniol-lck/modmanager#91]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

1.1.1

### Describe the bug (问题描述)

无法连接到curseforge，且mod因为网络原因更新检查失败

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Pico23th** [comment]
![截图_20220516194613](https://user-images.githubusercontent.com/93106088/168585942-abf91607-1ae8-4839-8035-4d0ee2ed2207.png)

**Comment by PurpleBeeZX** [comment]
同,解決了沒

**Comment by wjhwjbfj** [comment]
我这也是

**Comment by Hendrix-Shen** [comment]
mod manager所使用的api出了问题

**Comment by PurpleBeeZX** [comment]
現在有什麼代替方法嗎,比如説腳本之類的一鍵更新

**Comment by misaka10843** [comment]
有一说一都感觉作者都不更新这个了www（按照提交的频率来看的话

**Comment by Pico23th** [comment]
可以使用overwolf来更新 @PurpleBeeZX

**Comment by PurpleBeeZX** [comment]
> 可以使用overwolf来更新 @PurpleBeeZX

謝謝老哥

**Comment by successtheman** [comment]
though I don't understand any of this text I am experiencing the same issue/error I believe. Seems the curseforge API is not working as it was previously

**Comment by misaka10843** [comment]
> though I don't understand any of this text I am experiencing the same issue/error I believe. Seems the curseforge API is not working as it was previously

If it is to update the mod then you can use overwolf to temporarily update, but if it is necessary to search and so on then you can only wait for someone to fix it

---

如果是更新mod的话可以使用overwolf来暂时更新，但是如果是需要搜索等的话只能等人修复了

**Comment by misaka10843** [comment]
> ![1](https://user-images.githubusercontent.com/26178113/173181102-730582f3-2c57-4698-89bf-fc9d77adc20a.png) 能检查更新了

请问下这是原仓库exe还是您修改后的exe运行结果呢？

**Comment by ClementLevi** [comment]
同问题，先蹲一波修复或者fork

**Comment by PurpleBeeZX** [comment]
> > > ![1](https://user-images.githubusercontent.com/26178113/173181102-730582f3-2c57-4698-89bf-fc9d77adc20a.png) 能检查更新了
> > 
> > 
> > 请问下这是原仓库exe还是您修改后的exe运行结果呢？
> 
> 我改的，就改了一点，而且写的很难看，不知道该不该发上来
求

**Comment by misaka10843** [comment]
> > > ![1](https://user-images.githubusercontent.com/26178113/173181102-730582f3-2c57-4698-89bf-fc9d77adc20a.png) 能检查更新了
> > 
> > 
> > 请问下这是原仓库exe还是您修改后的exe运行结果呢？
> 
> 我改的，就改了一点，而且写的很难看，不知道该不该发上来

至少能与forge通信就行了🤣

**Comment by Lai-pishe** [comment]
> > > ![1](https://user-images.githubusercontent.com/26178113/173181102-730582f3-2c57-4698-89bf-fc9d77adc20a.png)能检查更新了
> > 
> > 
> > 下面是原仓库的exe还是您修改后的exe运行结果呢？
> 
> 我改的，就改了一点，而且写的难看，不知道该不该来

同求

**Comment by Forgot-Dream** [comment]
我稍微维护了一下 **写的不好轻喷** 
[https://github.com/Forgot-Dream/modmanager-qt/releases/tag/v1.1.1-build.8](https://github.com/Forgot-Dream/modmanager-qt/releases/tag/v1.1.1-build.8) 
主要**修复了Curseforge源失效和Modrinth源部分失效的问题**，并且维护了Mod更新功能

**Comment by MiniOrange101** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by PurpleBeeZX** [comment]
> 我稍微维护了一下 **写的不好轻喷** https://github.com/Forgot-Dream/modmanager-qt/releases/tag/v1.1.1-build.8 主要**修复了Curseforge源失效和Modrinth源部分失效的问题**，并且维护了Mod更新功能

好耶,謝謝老哥
