### ISSUE TITLE
什么时候更新

### ISSUE THREAD

**Issue by GodGun968** [kaniol-lck/modmanager#93]
### Question Type (问题类型)

Usage (使用)

### Describe the question (描述你的问题)

curseforge的api好像更新了

### Additional context (额外说明)

moderinth图片无法加载,mod无法更新

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my question.

**Comment by LITTLESITE** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/108331059/178882378-1cd0629e-d796-4b84-9155-03e7b544c587.png">
+1

**Comment by buiawpkgew1** [comment]
作者停更新了

**Comment by buiawpkgew1** [comment]
what

**Comment by GodGun968** [comment]
> what

?

**Comment by GodGun968** [comment]
?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kaniol-lck/modmanager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 上午9:38
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [kaniol-lck/modmanager] 什么时候更新 (Issue #93)





 
what
