### ISSUE TITLE
[Bug] Curseforge tab doesn't display anything

### ISSUE THREAD

**Issue by imh1kiko** [kaniol-lck/modmanager#95]
### OS Version (系统版本)

Windows

### Version Details (版本信息)

V1.1.1-build.543

### Describe the bug (问题描述)

In the Curseforge tab, nothing shows and reports "Failed loading" error.

### To Reproduce (复现问题)

Download latest build, try refreshing Curseforge, fail.

### Expected behavior (预期行为)

Lists mods on the Curseforge page.

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Additional context (额外说明)

Tried admin, nothing blocking, no mis-configuration.

**Comment by MiniOrange101** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by misaka10843** [comment]
you can use this fork https://github.com/Forgot-Dream/modmanager-qt
