### ISSUE TITLE
unknown access

### ISSUE THREAD

**Issue by yusufyyy** [kaniol-lck/modmanager#97]
why is this project page appearing on my search history without me accessing it? i accessed this page long long ago but didnt download anything.

![Screenshot (617)](https://github.com/kaniol-lck/modmanager/assets/58404312/27c5da01-6fb0-443e-be26-ade88fcc8e88)
![Screenshot (618)](https://github.com/kaniol-lck/modmanager/assets/58404312/841e5c54-9ded-4868-9df6-931f1a9c4b3f)
![Screenshot (619)](https://github.com/kaniol-lck/modmanager/assets/58404312/c3c8ad8f-35f5-4054-9abe-2472cd75cfed)

**Comment by MiniOrange101** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
